### ISSUE TITLE
add `homeConfigurations` schema

### ISSUE THREAD

**Issue by AshleyYakeley** [DeterminateSystems/flake-schemas#8]
Home Manager looks for this.

**Comment by srid** [comment]
Note that `legacyPackages.homeConfigurations` is also generally considered acceptable inasmuch as a perSystem `pkgs` is required. 

cf. https://github.com/srid/nixos-flake/blob/2c25190ceacdaaae7e8afbecfa87096bb499a431/examples/home/flake.nix#L25
